/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg.cig1;

import org.junit.Test;
import static org.junit.Assert.*;

public class InvoiceServiceTest {
    @Test public void testSomeLibraryMethod() {
        InvoiceService classUnderTest = new InvoiceService();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
